### ISSUE TITLE
comi does not run in Windows 10 64-bits in Fullscreen mode

### ISSUE THREAD

**Issue by lsenecaux** [bgbennyboy/Curse-Of-Monkey-Island-Setup-and-Launcher#1]
When I launch comi in fullscreen mode, I come back to Windows.
In windowed mode, it looks like to run, but the game hangs...

**Comment by bgbennyboy** [comment]
Use ScummVM. As I say on my website, its a much better solution

**Comment by lsenecaux** [comment]
What a pity, I found this really great initiative.

**Comment by bgbennyboy** [comment]
Its a replacement launcher and installer. I cant magically fix bugs with CMI and newer versions of Windows.
If you really dont want to use ScummVM then try playing with Windows compatibility modes (google it)

**Comment by lsenecaux** [comment]
It does not work.
I will use ScummVM for CoMI. 
Thanks for your work ;-)
